import { CartProvider } from '@/contexts/cart-context';
import './globals.css';
import type { Metadata } from 'next';
import { Radio_Canada_Big } from 'next/font/google';
import CartModal from '@/components/shared/cart-modal';
import RedirectingModal from '@/components/shared/redirecting-modal';
import { Suspense } from 'react';

const radioCanadaBig = Radio_Canada_Big({
  variable: '--font-radio-canada-big',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  icons: {
    icon: '/images/logo.png',
  },
  title: {
    default: 'Prep by Pros',
    template: '%s | Prep by Pros',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${radioCanadaBig.variable} antialiased`}>
        <Suspense fallback={<></>}>
          <CartProvider>
            {children}

            <CartModal />
            <RedirectingModal />
          </CartProvider>
        </Suspense>
      </body>
    </html>
  );
}
