import { PostDialog } from '@/app/(root)/creator/_components/post-dialog';
import CartModal from '@/components/shared/cart-modal';
import RedirectingModal from '@/components/shared/redirecting-modal';
import { CartProvider } from '@/contexts/cart-context';
import { PostDialogProvider } from '@/contexts/post-dialog-context';
import type { Metadata } from 'next';
import { Radio_Canada_Big } from 'next/font/google';
import { Suspense } from 'react';
import './globals.css';
import StoreProvider from './StoreProvider';

const radioCanadaBig = Radio_Canada_Big({
  variable: '--font-radio-canada-big',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  icons: {
    icon: '/images/logo.png',
  },
  title: {
    default: 'Prep by Pros',
    template: '%s | Prep by Pros',
  },
  description: 'Generated by create next app',
};

import AuthGuard from '@/components/auth/auth-guard';

// ... (imports remain the same)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${radioCanadaBig.variable} antialiased`} suppressHydrationWarning={true}>
        <Suspense fallback={<></>}>
          <StoreProvider>
            <CartProvider>
              <PostDialogProvider>
                <AuthGuard>{children}</AuthGuard>

                <PostDialog />
              </PostDialogProvider>

              <CartModal />
              <RedirectingModal />
            </CartProvider>
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
